"use strict";
exports.__esModule = true;
var auto_1 = require("./auto");
var autoDeportivo_1 = require("./autoDeportivo");
var autoCiudad_1 = require("./autoCiudad");
var primerAuto = new auto_1.Auto('Ford', 'Fiesta');
var autoViejo = new autoCiudad_1.AutoCiudad("Ford", "Falcon");
var superAuto = new autoDeportivo_1.AutoDeportivo('Ford', 'Mustang');
var superCar = new autoDeportivo_1.AutoDeportivo("Ferrari", "F50");
primerAuto.acelerar();
superAuto.acelerar();
console.log(primerAuto);
console.log(superAuto);
console.log("yo tengo un ", superAuto.getMarca(), " ", superAuto.getModelo());
console.log("...y yo tengo un ", superCar.getMarca(), " ", superCar.getModelo());
superCar.acelerar();
superCar.acelerar();
console.log(superCar);
autoViejo.acelerar();
console.log(autoViejo);
