"use strict";
exports.__esModule = true;
var legajoEscolar_1 = require("./legajoEscolar");
var examen_1 = require("./examen");
var alumno_1 = require("./alumno");
var legajo = new legajoEscolar_1["default"]("La Escuelita Adulta");
var examen1 = new examen_1["default"]("curso 1", "02082020");
var colegiado = new alumno_1["default"](12211, "Carlo", "Marxo", 30);
examen1.agregarAlumno(colegiado);
colegiado.agregarExamen(examen1);
examen1.setNotaAlumno(colegiado, 7);
var examen2 = new examen_1["default"]("curso 2", "02072020");
examen2.agregarAlumno(colegiado);
colegiado.agregarExamen(examen2);
examen2.setNotaAlumno(colegiado, 8);
var colegia2 = new alumno_1["default"](12213, "Jon", "Snow", 22);
examen1.agregarAlumno(colegia2);
colegia2.agregarExamen(examen1);
examen1.setNotaAlumno(colegia2, 4);
examen2.agregarAlumno(colegia2);
colegia2.agregarExamen(examen2);
examen2.setNotaAlumno(colegia2, 5);
legajo.agregar(colegiado);
console.log("promedio de ", colegiado.getNombreCompleto(), " es de: ", colegiado.calcularPromedio());
console.log("estudiante: ", colegiado);
// console.log("legajo: ",legajo);
legajo.agregar(colegia2);
console.log("promedio de ", colegia2.getNombreCompleto(), " es de: ", colegia2.calcularPromedio());
console.log("estudiante: ", colegia2);
console.log("legajo: ", legajo);
console.log("promedio de gral de alumnos en el instituto ", legajo.getInstitucion(), "es de: ", legajo.calcularPromedio());
